name: CI

on:
  push:
    branches:
    - CI-test

jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        version: 10

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
 
    - name: zip the archive
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -r deployment.zip ./build deploy.sh
    
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      env:
        USERNAME: ${{ secrets.SSH_USER }}
        HOST: ${{ secrets.SSH_HOST }}
        KEY: ${{ secrets.SSH_PRIV_KEY }}
      with:
        source: "deployment.zip"
        target: ".tmp"
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      env: 
        USERNAME: ${{ secrets.SSH_USER }}
        HOST: ${{ secrets.SSH_HOST }}
        KEY: ${{ secrets.SSH_PRIV_KEY }}
        SCRIPT: | 
          mkdir -p .tmp/$$
          mv .tmp/deployment.zip .tmp/$$/deployment.zip
          unzip -o .tmp/$$/deployment.zip -d .tmp/$$/
          cd .tmp/$$/ && bash deploy.sh pokedex
